[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = [
  "Backend/**"
]

[deploy]
startCommand = "/bin/sh -ec '/nakama/nakama migrate up --database.address \"$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$PGDATABASE?sslmode=require\" && exec /nakama/data/start-nakama.sh --database.address \"$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$PGDATABASE?sslmode=require\" --console.username \"$NAKAMA_CONSOLE_USERNAME\" --console.password \"$NAKAMA_CONSOLE_PASSWORD\" --console.signing_key \"$NAKAMA_CONSOLE_SIGNING_KEY\"'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
