[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = [
  "Backend/**"
]

[deploy]
startCommand = "/bin/sh -ec '/nakama/nakama migrate up --database.address \"$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$PGDATABASE?sslmode=require\" && exec /nakama/nakama --config /nakama/data/local.yml --database.address \"$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$PGDATABASE?sslmode=require\"'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
